//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 12/06/2018 13:35:42
namespace Grades.DataModel
{
    
    /// <summary>
    /// There are no comments for SchoolGradesDBEntities in the schema.
    /// </summary>
    public partial class SchoolGradesDBEntities : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new SchoolGradesDBEntities object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public SchoolGradesDBEntities(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for Grades in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Grade> Grades
        {
            get
            {
                if ((this._Grades == null))
                {
                    this._Grades = base.CreateQuery<Grade>("Grades");
                }
                return this._Grades;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Grade> _Grades;
        /// <summary>
        /// There are no comments for Students in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Student> Students
        {
            get
            {
                if ((this._Students == null))
                {
                    this._Students = base.CreateQuery<Student>("Students");
                }
                return this._Students;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Student> _Students;
        /// <summary>
        /// There are no comments for Subjects in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Subject> Subjects
        {
            get
            {
                if ((this._Subjects == null))
                {
                    this._Subjects = base.CreateQuery<Subject>("Subjects");
                }
                return this._Subjects;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Subject> _Subjects;
        /// <summary>
        /// There are no comments for Teachers in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Teacher> Teachers
        {
            get
            {
                if ((this._Teachers == null))
                {
                    this._Teachers = base.CreateQuery<Teacher>("Teachers");
                }
                return this._Teachers;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Teacher> _Teachers;
        /// <summary>
        /// There are no comments for Users in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<User> Users
        {
            get
            {
                if ((this._Users == null))
                {
                    this._Users = base.CreateQuery<User>("Users");
                }
                return this._Users;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<User> _Users;
        /// <summary>
        /// There are no comments for Grades in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToGrades(Grade grade)
        {
            base.AddObject("Grades", grade);
        }
        /// <summary>
        /// There are no comments for Students in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToStudents(Student student)
        {
            base.AddObject("Students", student);
        }
        /// <summary>
        /// There are no comments for Subjects in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToSubjects(Subject subject)
        {
            base.AddObject("Subjects", subject);
        }
        /// <summary>
        /// There are no comments for Teachers in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToTeachers(Teacher teacher)
        {
            base.AddObject("Teachers", teacher);
        }
        /// <summary>
        /// There are no comments for Users in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToUsers(User user)
        {
            base.AddObject("Users", user);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart0 = "<edmx:Edmx Version=\"1.0\" xmlns:edmx=\"http://schemas.microsoft.com/ado/2007/06/edm" +
                "x\"><edmx:DataServices m:DataServiceVersion=\"1.0\" m:MaxDataServiceVersion=\"3.0\" x" +
                "mlns:m=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\"><Schema " +
                "Namespace=\"SchoolGradesDBModel\" xmlns=\"http://schemas.microsoft.com/ado/2009/11/" +
                "edm\"><EntityType Name=\"Grade\"><Key><PropertyRef Name=\"Id\" /></Key><Property Name" +
                "=\"Id\" Type=\"Edm.Int32\" Nullable=\"false\" p6:StoreGeneratedPattern=\"Identity\" xmln" +
                "s:p6=\"http://schemas.microsoft.com/ado/2009/02/edm/annotation\" /><Property Name=" +
                "\"Assessment\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"Max\" FixedLength=\"fal" +
                "se\" Unicode=\"true\" /><Property Name=\"Comments\" Type=\"Edm.String\" MaxLength=\"Max\"" +
                " FixedLength=\"false\" Unicode=\"true\" /><Property Name=\"AssessmentDate\" Type=\"Edm." +
                "DateTime\" Nullable=\"false\" Precision=\"3\" /><Property Name=\"SubjectId\" Type=\"Edm." +
                "Int32\" Nullable=\"false\" /><Property Name=\"StudentUserId\" Type=\"Edm.Guid\" Nullabl" +
                "e=\"false\" /><NavigationProperty Name=\"Student\" Relationship=\"SchoolGradesDBModel" +
                ".FK_StudentGrade\" ToRole=\"Students\" FromRole=\"Grades\" /><NavigationProperty Name" +
                "=\"Subject\" Relationship=\"SchoolGradesDBModel.FK_SubjectGrade\" ToRole=\"Subjects\" " +
                "FromRole=\"Grades\" /></EntityType><EntityType Name=\"Student\"><Key><PropertyRef Na" +
                "me=\"UserId\" /></Key><Property Name=\"UserId\" Type=\"Edm.Guid\" Nullable=\"false\" /><" +
                "Property Name=\"FirstName\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"50\" Fixe" +
                "dLength=\"false\" Unicode=\"true\" /><Property Name=\"LastName\" Type=\"Edm.String\" Nul" +
                "lable=\"false\" MaxLength=\"50\" FixedLength=\"false\" Unicode=\"true\" /><Property Name" +
                "=\"ImageName\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"Max\" FixedLength=\"fal" +
                "se\" Unicode=\"true\" /><Property Name=\"TeacherUserId\" Type=\"Edm.Guid\" /><Navigatio" +
                "nProperty Name=\"Grades\" Relationship=\"SchoolGradesDBModel.FK_StudentGrade\" ToRol" +
                "e=\"Grades\" FromRole=\"Students\" /><NavigationProperty Name=\"User\" Relationship=\"S" +
                "choolGradesDBModel.FK_Students_diameterUsers\" ToRole=\"Users\" FromRole=\"Students\"" +
                " /><NavigationProperty Name=\"Teacher\" Relationship=\"SchoolGradesDBModel.FK_Teach" +
                "erStudent\" ToRole=\"Teachers\" FromRole=\"Students\" /></EntityType><EntityType Name" +
                "=\"Subject\"><Key><PropertyRef Name=\"Id\" /></Key><Property Name=\"Id\" Type=\"Edm.Int" +
                "32\" Nullable=\"false\" /><Property Name=\"Name\" Type=\"Edm.String\" Nullable=\"false\" " +
                "MaxLength=\"Max\" FixedLength=\"false\" Unicode=\"true\" /><NavigationProperty Name=\"G" +
                "rades\" Relationship=\"SchoolGradesDBModel.FK_SubjectGrade\" ToRole=\"Grades\" FromRo" +
                "le=\"Subjects\" /></EntityType><EntityType Name=\"Teacher\"><Key><PropertyRef Name=\"" +
                "UserId\" /></Key><Property Name=\"UserId\" Type=\"Edm.Guid\" Nullable=\"false\" /><Prop" +
                "erty Name=\"FirstName\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"50\" FixedLen" +
                "gth=\"false\" Unicode=\"true\" /><Property Name=\"LastName\" Type=\"Edm.String\" Nullabl" +
                "e=\"false\" MaxLength=\"50\" FixedLength=\"false\" Unicode=\"true\" /><Property Name=\"Cl" +
                "ass\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"20\" FixedLength=\"false\" Unico" +
                "de=\"true\" /><NavigationProperty Name=\"Students\" Relationship=\"SchoolGradesDBMode" +
                "l.FK_TeacherStudent\" ToRole=\"Students\" FromRole=\"Teachers\" /><NavigationProperty" +
                " Name=\"User\" Relationship=\"SchoolGradesDBModel.FK_Teachers_diameterUsers\" ToRole" +
                "=\"Users\" FromRole=\"Teachers\" /></EntityType><EntityType Name=\"User\"><Key><Proper" +
                "tyRef Name=\"UserId\" /></Key><Property Name=\"ApplicationId\" Type=\"Edm.Guid\" Nulla" +
                "ble=\"false\" /><Property Name=\"UserId\" Type=\"Edm.Guid\" Nullable=\"false\" /><Proper" +
                "ty Name=\"UserName\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"50\" FixedLength" +
                "=\"false\" Unicode=\"true\" /><Property Name=\"IsAnonymous\" Type=\"Edm.Boolean\" Nullab" +
                "le=\"false\" /><Property Name=\"LastActivityDate\" Type=\"Edm.DateTime\" Nullable=\"fal" +
                "se\" Precision=\"3\" /><Property Name=\"UserPassword\" Type=\"Edm.String\" Nullable=\"fa" +
                "lse\" MaxLength=\"20\" FixedLength=\"false\" Unicode=\"true\" /><NavigationProperty Nam" +
                "e=\"Student\" Relationship=\"SchoolGradesDBModel.FK_Students_diameterUsers\" ToRole=" +
                "\"Students\" FromRole=\"Users\" /><NavigationProperty Name=\"Teacher\" Relationship=\"S" +
                "choolGradesDBModel.FK_Teachers_diameterUsers\" ToRole=\"Teachers\" FromRole=\"Users\"" +
                " /></EntityType><Association Name=\"FK_StudentGrade\"><End Type=\"SchoolGradesDBMod" +
                "el.Student\" Role=\"Students\" Multiplicity=\"1\" /><End Type=\"SchoolGradesDBModel.Gr" +
                "ade\" Role=\"Grades\" Multiplicity=\"*\" /><ReferentialConstraint><Principal Role=\"St" +
                "udents\"><PropertyRef Name=\"UserId\" /></Principal><Dependent Role=\"Grades\"><Prope" +
                "rtyRef Name=\"StudentUserId\" /></Dependent></ReferentialConstraint></Association>" +
                "<Association Name=\"FK_SubjectGrade\"><End Type=\"SchoolGradesDBModel.Subject\" Role" +
                "=\"Subjects\" Multiplicity=\"1\" /><End Type=\"SchoolGradesDBModel.Grade\" Role=\"Grade" +
                "s\" Multiplicity=\"*\" /><ReferentialConstraint><Principal Role=\"Subjects\"><Propert" +
                "yRef Name=\"Id\" /></Principal><Dependent Role=\"Grades\"><PropertyRef Name=\"Subject" +
                "Id\" /></Dependent></ReferentialConstraint></Association><Association Name=\"FK_St" +
                "udents_diameterUsers\"><End Type=\"SchoolGradesDBModel.User\" Role=\"Users\" Multipli" +
                "city=\"1\" /><End Type=\"SchoolGradesDBModel.Student\" Role=\"Students\" Multiplicity=" +
                "\"0..1\" /><ReferentialConstraint><Principal Role=\"Users\"><PropertyRef Name=\"UserI" +
                "d\" /></Principal><Dependent Role=\"Students\"><PropertyRef Name=\"UserId\" /></Depen" +
                "dent></ReferentialConstraint></Association><Association Name=\"FK_TeacherStudent\"" +
                "><End Type=\"SchoolGradesDBModel.Teacher\" Role=\"Teachers\" Multiplicity=\"0..1\" /><" +
                "End Type=\"SchoolGradesDBModel.Student\" Role=\"Students\" Multiplicity=\"*\" /><Refer" +
                "entialConstraint><Principal Role=\"Teachers\"><PropertyRef Name=\"UserId\" /></Princ" +
                "ipal><Dependent Role=\"Students\"><PropertyRef Name=\"TeacherUserId\" /></Dependent>" +
                "</ReferentialConstraint></Association><Association Name=\"FK_Teachers_diameterUse" +
                "rs\"><End Type=\"SchoolGradesDBModel.User\" Role=\"Users\" Multiplicity=\"1\" /><End Ty" +
                "pe=\"SchoolGradesDBModel.Teacher\" Role=\"Teachers\" Multiplicity=\"0..1\" /><Referent" +
                "ialConstraint><Principal Role=\"Users\"><PropertyRef Name=\"UserId\" /></Principal><" +
                "Dependent Role=\"Teachers\"><PropertyRef Name=\"UserId\" /></Dependent></Referential" +
                "Constraint></Association></Schema><Schema Namespace=\"Grades.DataModel\" xmlns=\"ht" +
                "tp://schemas.microsoft.com/ado/2009/11/edm\"><EntityContainer Name=\"SchoolGradesD" +
                "BEntities\" m:IsDefaultEntityContainer=\"true\" p6:LazyLoadingEnabled=\"true\" xmlns:" +
                "p6=\"http://schemas.microsoft.com/ado/2009/02/edm/annotation\"><EntitySet Name=\"Gr" +
                "ades\" EntityType=\"SchoolGradesDBModel.Grade\" /><EntitySet Name=\"Students\" Entity" +
                "Type=\"SchoolGradesDBModel.Student\" /><EntitySet Name=\"Subjects\" EntityType=\"Scho" +
                "olGradesDBModel.Subject\" /><EntitySet Name=\"Teachers\" EntityType=\"SchoolGradesDB" +
                "Model.Teacher\" /><EntitySet Name=\"Users\" EntityType=\"SchoolGradesDBModel.User\" /" +
                "><FunctionImport Name=\"StudentsInClass\" ReturnType=\"Collection(SchoolGradesDBMod" +
                "el.Student)\" EntitySet=\"Students\" m:HttpMethod=\"GET\"><Parameter Name=\"className\"" +
                " Type=\"Edm.String\" /></FunctionImport><AssociationSet Name=\"FK_StudentGrade\" Ass" +
                "ociation=\"SchoolGradesDBModel.FK_StudentGrade\"><End Role=\"Grades\" EntitySet=\"Gra" +
                "des\" /><End Role=\"Students\" EntitySet=\"Students\" /></AssociationSet><Association" +
                "Set Name=\"FK_SubjectGrade\" Association=\"SchoolGradesDBModel.FK_SubjectGrade\"><En" +
                "d Role=\"Grades\" EntitySet=\"Grades\" /><End Role=\"Subjects\" EntitySet=\"Subjects\" /" +
                "></AssociationSet><AssociationSet Name=\"FK_Students_diameterUsers\" Association=\"" +
                "SchoolGradesDBModel.FK_Students_diameterUsers\"><End Role=\"Students\" EntitySet=\"S" +
                "tudents\" /><End Role=\"Users\" EntitySet=\"Users\" /></AssociationSet><AssociationSe" +
                "t Name=\"FK_TeacherStudent\" Association=\"SchoolGradesDBModel";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart1 = @".FK_TeacherStudent""><End Role=""Students"" EntitySet=""Students"" /><End Role=""Teachers"" EntitySet=""Teachers"" /></AssociationSet><AssociationSet Name=""FK_Teachers_diameterUsers"" Association=""SchoolGradesDBModel.FK_Teachers_diameterUsers""><End Role=""Teachers"" EntitySet=""Teachers"" /><End Role=""Users"" EntitySet=""Users"" /></AssociationSet></EntityContainer></Schema></edmx:DataServices></edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static string GetConcatenatedEdmxString()
            {
                return string.Concat(ModelPart0, ModelPart1);
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            public static global::Microsoft.Data.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel LoadModelFromString()
            {
                string edmxToParse = GetConcatenatedEdmxString();
                global::System.Xml.XmlReader reader = CreateXmlReader(edmxToParse);
                try
                {
                    return global::Microsoft.Data.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// There are no comments for SchoolGradesDBModel.Grade in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Grades")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Grade : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Grade object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="assessment">Initial value of Assessment.</param>
        /// <param name="assessmentDate">Initial value of AssessmentDate.</param>
        /// <param name="subjectId">Initial value of SubjectId.</param>
        /// <param name="studentUserId">Initial value of StudentUserId.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Grade CreateGrade(int ID, string assessment, global::System.DateTime assessmentDate, int subjectId, global::System.Guid studentUserId)
        {
            Grade grade = new Grade();
            grade.Id = ID;
            grade.Assessment = assessment;
            grade.AssessmentDate = assessmentDate;
            grade.SubjectId = subjectId;
            grade.StudentUserId = studentUserId;
            return grade;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Assessment in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Assessment
        {
            get
            {
                return this._Assessment;
            }
            set
            {
                this.OnAssessmentChanging(value);
                this._Assessment = value;
                this.OnAssessmentChanged();
                this.OnPropertyChanged("Assessment");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Assessment;
        partial void OnAssessmentChanging(string value);
        partial void OnAssessmentChanged();
        /// <summary>
        /// There are no comments for Property Comments in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Comments
        {
            get
            {
                return this._Comments;
            }
            set
            {
                this.OnCommentsChanging(value);
                this._Comments = value;
                this.OnCommentsChanged();
                this.OnPropertyChanged("Comments");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Comments;
        partial void OnCommentsChanging(string value);
        partial void OnCommentsChanged();
        /// <summary>
        /// There are no comments for Property AssessmentDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime AssessmentDate
        {
            get
            {
                return this._AssessmentDate;
            }
            set
            {
                this.OnAssessmentDateChanging(value);
                this._AssessmentDate = value;
                this.OnAssessmentDateChanged();
                this.OnPropertyChanged("AssessmentDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _AssessmentDate;
        partial void OnAssessmentDateChanging(global::System.DateTime value);
        partial void OnAssessmentDateChanged();
        /// <summary>
        /// There are no comments for Property SubjectId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int SubjectId
        {
            get
            {
                return this._SubjectId;
            }
            set
            {
                this.OnSubjectIdChanging(value);
                this._SubjectId = value;
                this.OnSubjectIdChanged();
                this.OnPropertyChanged("SubjectId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _SubjectId;
        partial void OnSubjectIdChanging(int value);
        partial void OnSubjectIdChanged();
        /// <summary>
        /// There are no comments for Property StudentUserId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid StudentUserId
        {
            get
            {
                return this._StudentUserId;
            }
            set
            {
                this.OnStudentUserIdChanging(value);
                this._StudentUserId = value;
                this.OnStudentUserIdChanged();
                this.OnPropertyChanged("StudentUserId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _StudentUserId;
        partial void OnStudentUserIdChanging(global::System.Guid value);
        partial void OnStudentUserIdChanged();
        /// <summary>
        /// There are no comments for Student in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Student Student
        {
            get
            {
                return this._Student;
            }
            set
            {
                this._Student = value;
                this.OnPropertyChanged("Student");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Student _Student;
        /// <summary>
        /// There are no comments for Subject in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Subject Subject
        {
            get
            {
                return this._Subject;
            }
            set
            {
                this._Subject = value;
                this.OnPropertyChanged("Subject");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Subject _Subject;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for SchoolGradesDBModel.Student in the schema.
    /// </summary>
    /// <KeyProperties>
    /// UserId
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Students")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("UserId")]
    public partial class Student : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Student object.
        /// </summary>
        /// <param name="userId">Initial value of UserId.</param>
        /// <param name="firstName">Initial value of FirstName.</param>
        /// <param name="lastName">Initial value of LastName.</param>
        /// <param name="imageName">Initial value of ImageName.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Student CreateStudent(global::System.Guid userId, string firstName, string lastName, string imageName)
        {
            Student student = new Student();
            student.UserId = userId;
            student.FirstName = firstName;
            student.LastName = lastName;
            student.ImageName = imageName;
            return student;
        }
        /// <summary>
        /// There are no comments for Property UserId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid UserId
        {
            get
            {
                return this._UserId;
            }
            set
            {
                this.OnUserIdChanging(value);
                this._UserId = value;
                this.OnUserIdChanged();
                this.OnPropertyChanged("UserId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _UserId;
        partial void OnUserIdChanging(global::System.Guid value);
        partial void OnUserIdChanged();
        /// <summary>
        /// There are no comments for Property FirstName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string FirstName
        {
            get
            {
                return this._FirstName;
            }
            set
            {
                this.OnFirstNameChanging(value);
                this._FirstName = value;
                this.OnFirstNameChanged();
                this.OnPropertyChanged("FirstName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _FirstName;
        partial void OnFirstNameChanging(string value);
        partial void OnFirstNameChanged();
        /// <summary>
        /// There are no comments for Property LastName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string LastName
        {
            get
            {
                return this._LastName;
            }
            set
            {
                this.OnLastNameChanging(value);
                this._LastName = value;
                this.OnLastNameChanged();
                this.OnPropertyChanged("LastName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _LastName;
        partial void OnLastNameChanging(string value);
        partial void OnLastNameChanged();
        /// <summary>
        /// There are no comments for Property ImageName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ImageName
        {
            get
            {
                return this._ImageName;
            }
            set
            {
                this.OnImageNameChanging(value);
                this._ImageName = value;
                this.OnImageNameChanged();
                this.OnPropertyChanged("ImageName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ImageName;
        partial void OnImageNameChanging(string value);
        partial void OnImageNameChanged();
        /// <summary>
        /// There are no comments for Property TeacherUserId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.Guid> TeacherUserId
        {
            get
            {
                return this._TeacherUserId;
            }
            set
            {
                this.OnTeacherUserIdChanging(value);
                this._TeacherUserId = value;
                this.OnTeacherUserIdChanged();
                this.OnPropertyChanged("TeacherUserId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.Guid> _TeacherUserId;
        partial void OnTeacherUserIdChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnTeacherUserIdChanged();
        /// <summary>
        /// There are no comments for Grades in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Grade> Grades
        {
            get
            {
                return this._Grades;
            }
            set
            {
                this._Grades = value;
                this.OnPropertyChanged("Grades");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Grade> _Grades = new global::System.Data.Services.Client.DataServiceCollection<Grade>(null, global::System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// There are no comments for User in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public User User
        {
            get
            {
                return this._User;
            }
            set
            {
                this._User = value;
                this.OnPropertyChanged("User");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private User _User;
        /// <summary>
        /// There are no comments for Teacher in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Teacher Teacher
        {
            get
            {
                return this._Teacher;
            }
            set
            {
                this._Teacher = value;
                this.OnPropertyChanged("Teacher");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Teacher _Teacher;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for SchoolGradesDBModel.Subject in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Subjects")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Subject : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Subject object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="name">Initial value of Name.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Subject CreateSubject(int ID, string name)
        {
            Subject subject = new Subject();
            subject.Id = ID;
            subject.Name = name;
            return subject;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Grades in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Grade> Grades
        {
            get
            {
                return this._Grades;
            }
            set
            {
                this._Grades = value;
                this.OnPropertyChanged("Grades");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Grade> _Grades = new global::System.Data.Services.Client.DataServiceCollection<Grade>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for SchoolGradesDBModel.Teacher in the schema.
    /// </summary>
    /// <KeyProperties>
    /// UserId
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Teachers")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("UserId")]
    public partial class Teacher : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Teacher object.
        /// </summary>
        /// <param name="userId">Initial value of UserId.</param>
        /// <param name="firstName">Initial value of FirstName.</param>
        /// <param name="lastName">Initial value of LastName.</param>
        /// <param name="class">Initial value of Class.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Teacher CreateTeacher(global::System.Guid userId, string firstName, string lastName, string @class)
        {
            Teacher teacher = new Teacher();
            teacher.UserId = userId;
            teacher.FirstName = firstName;
            teacher.LastName = lastName;
            teacher.Class = @class;
            return teacher;
        }
        /// <summary>
        /// There are no comments for Property UserId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid UserId
        {
            get
            {
                return this._UserId;
            }
            set
            {
                this.OnUserIdChanging(value);
                this._UserId = value;
                this.OnUserIdChanged();
                this.OnPropertyChanged("UserId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _UserId;
        partial void OnUserIdChanging(global::System.Guid value);
        partial void OnUserIdChanged();
        /// <summary>
        /// There are no comments for Property FirstName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string FirstName
        {
            get
            {
                return this._FirstName;
            }
            set
            {
                this.OnFirstNameChanging(value);
                this._FirstName = value;
                this.OnFirstNameChanged();
                this.OnPropertyChanged("FirstName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _FirstName;
        partial void OnFirstNameChanging(string value);
        partial void OnFirstNameChanged();
        /// <summary>
        /// There are no comments for Property LastName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string LastName
        {
            get
            {
                return this._LastName;
            }
            set
            {
                this.OnLastNameChanging(value);
                this._LastName = value;
                this.OnLastNameChanged();
                this.OnPropertyChanged("LastName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _LastName;
        partial void OnLastNameChanging(string value);
        partial void OnLastNameChanged();
        /// <summary>
        /// There are no comments for Property Class in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Class
        {
            get
            {
                return this._Class;
            }
            set
            {
                this.OnClassChanging(value);
                this._Class = value;
                this.OnClassChanged();
                this.OnPropertyChanged("Class");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Class;
        partial void OnClassChanging(string value);
        partial void OnClassChanged();
        /// <summary>
        /// There are no comments for Students in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Student> Students
        {
            get
            {
                return this._Students;
            }
            set
            {
                this._Students = value;
                this.OnPropertyChanged("Students");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Student> _Students = new global::System.Data.Services.Client.DataServiceCollection<Student>(null, global::System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// There are no comments for User in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public User User
        {
            get
            {
                return this._User;
            }
            set
            {
                this._User = value;
                this.OnPropertyChanged("User");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private User _User;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for SchoolGradesDBModel.User in the schema.
    /// </summary>
    /// <KeyProperties>
    /// UserId
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Users")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("UserId")]
    public partial class User : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="applicationId">Initial value of ApplicationId.</param>
        /// <param name="userId">Initial value of UserId.</param>
        /// <param name="userName">Initial value of UserName.</param>
        /// <param name="isAnonymous">Initial value of IsAnonymous.</param>
        /// <param name="lastActivityDate">Initial value of LastActivityDate.</param>
        /// <param name="userPassword">Initial value of UserPassword.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static User CreateUser(global::System.Guid applicationId, global::System.Guid userId, string userName, bool isAnonymous, global::System.DateTime lastActivityDate, string userPassword)
        {
            User user = new User();
            user.ApplicationId = applicationId;
            user.UserId = userId;
            user.UserName = userName;
            user.IsAnonymous = isAnonymous;
            user.LastActivityDate = lastActivityDate;
            user.UserPassword = userPassword;
            return user;
        }
        /// <summary>
        /// There are no comments for Property ApplicationId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid ApplicationId
        {
            get
            {
                return this._ApplicationId;
            }
            set
            {
                this.OnApplicationIdChanging(value);
                this._ApplicationId = value;
                this.OnApplicationIdChanged();
                this.OnPropertyChanged("ApplicationId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _ApplicationId;
        partial void OnApplicationIdChanging(global::System.Guid value);
        partial void OnApplicationIdChanged();
        /// <summary>
        /// There are no comments for Property UserId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid UserId
        {
            get
            {
                return this._UserId;
            }
            set
            {
                this.OnUserIdChanging(value);
                this._UserId = value;
                this.OnUserIdChanged();
                this.OnPropertyChanged("UserId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _UserId;
        partial void OnUserIdChanging(global::System.Guid value);
        partial void OnUserIdChanged();
        /// <summary>
        /// There are no comments for Property UserName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string UserName
        {
            get
            {
                return this._UserName;
            }
            set
            {
                this.OnUserNameChanging(value);
                this._UserName = value;
                this.OnUserNameChanged();
                this.OnPropertyChanged("UserName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _UserName;
        partial void OnUserNameChanging(string value);
        partial void OnUserNameChanged();
        /// <summary>
        /// There are no comments for Property IsAnonymous in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool IsAnonymous
        {
            get
            {
                return this._IsAnonymous;
            }
            set
            {
                this.OnIsAnonymousChanging(value);
                this._IsAnonymous = value;
                this.OnIsAnonymousChanged();
                this.OnPropertyChanged("IsAnonymous");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _IsAnonymous;
        partial void OnIsAnonymousChanging(bool value);
        partial void OnIsAnonymousChanged();
        /// <summary>
        /// There are no comments for Property LastActivityDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime LastActivityDate
        {
            get
            {
                return this._LastActivityDate;
            }
            set
            {
                this.OnLastActivityDateChanging(value);
                this._LastActivityDate = value;
                this.OnLastActivityDateChanged();
                this.OnPropertyChanged("LastActivityDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _LastActivityDate;
        partial void OnLastActivityDateChanging(global::System.DateTime value);
        partial void OnLastActivityDateChanged();
        /// <summary>
        /// There are no comments for Property UserPassword in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string UserPassword
        {
            get
            {
                return this._UserPassword;
            }
            set
            {
                this.OnUserPasswordChanging(value);
                this._UserPassword = value;
                this.OnUserPasswordChanged();
                this.OnPropertyChanged("UserPassword");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _UserPassword;
        partial void OnUserPasswordChanging(string value);
        partial void OnUserPasswordChanged();
        /// <summary>
        /// There are no comments for Student in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Student Student
        {
            get
            {
                return this._Student;
            }
            set
            {
                this._Student = value;
                this.OnPropertyChanged("Student");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Student _Student;
        /// <summary>
        /// There are no comments for Teacher in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Teacher Teacher
        {
            get
            {
                return this._Teacher;
            }
            set
            {
                this._Teacher = value;
                this.OnPropertyChanged("Teacher");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Teacher _Teacher;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
